### ISSUE TITLE
How to add plugins to this ckeditor

### ISSUE THREAD

**Issue by thamibn** [ckeditor/ckeditor5-vue#127]
I have followed the guide on using ckeditor from source, but it is giving me errors about the theme module not found.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In order to solve this issue, I need to know exact steps that you followed, your editor configuration and what is the error message. Please also make sure that you followed our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html).

**Comment by thamibn** [comment]
@FilipTokarski thanks for your reply i have a open issues here with all the steps i have followed https://github.com/ckeditor/ckeditor5/issues/6298

**Comment by FilipTokarski** [comment]
Ok, thanks. So I will close this one as a duplicate and take a look at the issue you linked
