### ISSUE TITLE
 Cannot read property 'change' of undefined 

### ISSUE THREAD

**Issue by mw-shublaq** [ckeditor/ckeditor5-vue#145]
## 📝 Provide detailed reproduction steps (if any)
I'm using VueJs 2.6 alongside with these packages
```
"@ckeditor/ckeditor5-build-classic": "^11.2.0",
"@ckeditor/ckeditor5-vue": "^1.0.0-beta.1",
```

I'm trying to insert some texts to the editor, but this error occurs `Cannot read property 'change' of undefined`
My scenario is that I have a button when the user clicks on it should insert the predefined text into the editor.
here is a snippet:

template section:

```
<div>
    <button  id="addTag" @click="addTag()">
       Click me
    </button>

      <ckeditor
           :editor="editor"
	    v-model="message"
      ></ckeditor>
</div>
```

script section:
```
<script>
import CKEditor from "@ckeditor/ckeditor5-vue";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
export default {
         components: {
		ckeditor: CKEditor.component,
		expressionBuilder,
          },
          data() {
                message: "",
                editor: ClassicEditor,
           },
           methods: {
                 addTag() {
			this.editor.model.change((writer) => {
				const insertPosition = this.editor.model.document.selection.getFirstPosition();
				writer.insertText("CKEditor 5 rocks!", insertPosition);
			});
		},
            }
}
```

Error returned and stops the application from inserting
## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. The problem here is that `this.editor` in `addTag` is not the editor instance, hence you get this error. To pass the editor instance to your method, you need to do a few things. 
First, you need to add [_ready event_](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#ready) on the editor component:  
```html
<ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @ready="onEditorReady"></ckeditor>
```
Next, create `onEditorReady` method, so when the editor loads, it will be called ( passing inside the editor instance ). I tried to follow your use case, so I created a `button` that has `eventListener` firing this `addTag` function on click:  
```js
methods: {
            onEditorReady( editor ){
                document.querySelector( '.add-text' ).addEventListener( 'click', () => {
                    this.addTag( editor );
                } );
            },
        ...
```
And finally the `addTag` method:
```js
addTag( editor ) {
          editor.model.change( writer => {
                  const insertPosition = editor.model.document.selection.getFirstPosition();
                  writer.insertText("CKEditor 5 rocks!", insertPosition);
          });
},
```
This is some basic implementation, so you can further adjust it to your needs. Hope that helps!

**Comment by FilipTokarski** [comment]
Closed due to lack of feedback.
