### ISSUE TITLE
Focus issue when adding TableProperties and TableCellProperties

### ISSUE THREAD

**Issue by thorleifjaocbsen** [ckeditor/ckeditor5-vue#180]
Hi

I've added TP and TCP to my Vue page, it works perfectly and looks really good. But when I enter the properties and try to press the text fields it quickly looses focus. Any idea on where to start to figure out what this is? Is it a bug in the editor for Vue?

https://user-images.githubusercontent.com/8550684/111754548-696ba180-8898-11eb-9498-77c4914eda96.mp4

**Comment by FilipTokarski** [comment]
Hi, I just checked Vue integration with `TableProperties` and `TableCellProperties` plugins and it works fine for me. So I would advise to double check whether this might be caused by your app/environment in which you use the editor. 
 If that's not the case, we'll need more information to reproduce this issue ( precise step-by-step description, editor configuration, packages used, custom code, etc. )

**Comment by thorleifjaocbsen** [comment]
You know what, 4 hours of my workday went into this issue. I managed to figure out it was v-dialog from vuetify which had an eventlistener to keep focus on the one dialog. So when ckeditor open a new one  the focus went straight back.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/8550684/111842678-1b8a8400-8900-11eb-9d11-3d7da4b83021.png">

Luckily they had an prop for disabling it.

This issue (non-issue) can be closed! Hope to help someone else struggeling with the same thing!
