### ISSUE TITLE
Insert content at cursor position throws error

### ISSUE THREAD

**Issue by ThomasTr** [ckeditor/ckeditor5-vue#183]
When i try to insert content at cursor position with this code:
```
this.editor.model.change(writer => {
    writer.insertText(variable, this.editor.model.document.selection.getFirstPosition());
});
```
I get this error:
```
Uncaught TypeError: 'get' on proxy: property '_events' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')
```
The exact same code worked on vue2. I get access to the editor object via `@ready="onEditorReady` and this method:
```
onEditorReady(editor) {
    this.editor = editor;
},
```

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I checked it and had no problem when using the editor api through the consolewhen wxposing editor in:
```js
```

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I checked this case first with exposing editor like this:
```js
onEditorReady(editor) {
    window.editor = editor;
}
```
and using it in console - and then it worked fine in both versions.  
  
But when I created a button and an additional method for inserting content, I got the same results - it works fine in component for Vue 2 but fails in Vue 3 with the same error message.

**Comment by psmyrek** [comment]
The problem here is in the reactivity system introduced in Vue 3, which is now based on proxies. The reason it works fine with Vue 2 is that it is using different reactivity system - based on `Object.defineProperty` API. When an object with non-writable and non-configurable properties is set in the `data`, Vue 2 simply just skips such properties making them non-reactive. However, Vue 3 tries to convert the whole object to a proxy to be able to detect all changes in it and it does not play well with non-writable and non-configurable properties. This is already reported as an issue in Vue: https://github.com/vuejs/vue-next/issues/3024.

Workarounds:
* IMHO it doesn't make much sense to store the editor instance in the `data` and to force Vue to detect all changes within it. I don't know your exact use case, but maybe using local variables would be sufficient.
* If you still need to store the editor instance in the `data`, you can use [`markRaw()`](https://v3.vuejs.org/api/basic-reactivity.html#markraw) method to explicitly tell Vue to never convert it to a proxy. The code snippet would look like:

```javascript
import { markRaw } from 'vue';

onEditorReady(editor) {
    this.editor = markRaw(editor);
}
```

There is nothing we can do on our side, so I'm closing this issue.

**Comment by ThomasTr** [comment]
Thanks @psmyrek for your deep insights into vue, really interesting. I've followed your first advise, using just an local variable, and it works 👍
