### ISSUE TITLE
Error when mounting and setting the editorData

### ISSUE THREAD

**Issue by jonvanputten** [ckeditor/ckeditor5-vue#33]
So here is the case:
``` vue
<template>
    <div>
        <ckeditor 
            :editor="editor" 
            v-model="editorData"
            :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
export default {
    name: "something",
    data() {
        return {
            // CKEditer 
            editor: ClassicEditor,
            editorData: '',
            editorConfig: {
                // The configuration of the editor.
                toolbar: [ 'bold', 'italic' ]
            },
        };
    },
    watch: {
        editorData: function(val) {
            this.$emit('input', val);
        },
    },
    mounted() {
        this.editorData = "Prefill with data here";
    }
};
</script>
```

When I switch components or view that contains the CKEditor, the data gets filled with no problem when mounted, but keeps giving an error in the console:
```
[Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'getData' of null"
```
Any ideas on this? Am I implementing it right or is it a bug?

**Comment by bubgdgnanh** [comment]
I got the same issue. Do someone have a solution for this case?

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Editor initialization is asynchronous (returns a promise) and fires an event when the editor is ready.

When you use `mounted() {` to set data, it tries to set the instance data **before** the editor instance comes into existence.

Use the [@ready](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#ready) component listener to do that instead to guarantee the editor is up and running. 

```html
<ckeditor
	:editor="editor"
	v-model="editorData"
	:config="editorConfig"
	@ready="prefill"
></ckeditor>
```

```js
const app = new Vue( {
	// ...

	watch: {
		editorData: function( val ) {
			this.$emit('input', val);
		},
	},
	methods: {
		prefill( editor ) {
			this.editorData = "Prefill with data here";
		}
	}
} );
```

**Comment by jonvanputten** [comment]
@oleq Your suggestion did the trick! Thanks for the answer and good to know whats going on behind the editor!

**Comment by Ragash** [comment]
Hello! 
I'm facing a problem similar to this, but it's related to the hooks of vue.

In my view I'm setting a form data with a beforeRouteEnter to get info from an api, from there I'm calling a local setData method to populate my local variables.

The problem is that my variables get populated before the ckeditor is ready, and this causes the very same error.

For now I solved the issue defining an extra variable ( "editorData") and filling from my retrieved local variables with a @ready method.
The same is done with a @input to update my variables back

But still it seems very wonky to me, why I should define a v-model to my editor component if the simple task of filling it during routing breaks the whole thing?
What am I missing?

I will provide some code later, right now I'm not at the pc.
Thanks for your time!
