### ISSUE TITLE
Building (balloon) editor from source gives model-nodelist-offset-out-of-bounds

### ISSUE THREAD

**Issue by ChristophWurst** [ckeditor/ckeditor5-vue#94]
Hi :wave:

I'm trying to integrate CKEditor into our FLOSS product https://github.com/nextcloud/mail. After some successful experiments with the prebuilt version I've read https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source and followed it to get a multi-lang version of the balloon editor. Since we're not using Vue CLI I adapted the configuration into our webpack config. Regardless of the editor (classic or balloon) used, I always get a 

> Error: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…t/error-codes.html#error-model-nodelist-offset-out-of-bounds
 {"offset":1,"nodeList":[]}

as soon as I focus the editor and hit a key. The referenced documentation does not give me a clue about my problem. As far as I understood this custom position mapping should not be necessary with the basic editor and no custom plugins.

There were no other tickets with this problem, so I opened a new one.

My code can be found here: https://github.com/nextcloud/mail/pull/1988/files

This is my first ticket in this repo. Please let me know if you need any other information.

Thanks :)

**Comment by Mgsy** [comment]
Hi @ChristophWurst! We're really happy that you chose CKEditor 5 :)

I've analyzed your code and it seems that the problem occurs because you didn't attach the paragraph plugin, so the editor initializes without a paragraph element which is required for typing. 

To fix it, install the paragraph plugin package:
```
npm install --save @ckeditor/ckeditor5-paragraph
```

then, [add it to the editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor) and rebuild it. 

Let us know if it helped and feel free to reach us in case of any further questions :)

**Comment by ChristophWurst** [comment]
Yes, this fixed the problem! Thank so you much for the quick help! I should have gone with the full featured version before removing stuff we don't need. It wasn't clear that the paragraph plugin is required.

Thanks :rocket:
