### ISSUE TITLE
Is config passed to ckeditor responsive?

### ISSUE THREAD

**Issue by NegativeDearc** [ckeditor/ckeditor5-vue#99]
Hello, I passed the uid from props, but `this.uid` in the config passed to editor showed as undefined

Is it responsive ?

```
 simpleUpload: {
          // Upload the images to the server using the QuickUpload command.
          // todo: the this.uid is null
          uploadUrl: `${this.axios.defaults.baseURL}` + `/upload/` + `${this.uid}` || 'upload',
          // Headers sent along with the XMLHttpRequest to the upload server.
          headers: {
            Authorization: `Bearer ${this.$store.getters.accessToken}`
          }
        },
```

**Comment by Mgsy** [comment]
Hi, can you show us how you passed `uid` to the editor?

**Comment by NegativeDearc** [comment]
I just pass `uid` from `props`.

**Comment by oleq** [comment]
The [editor config](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html) is always read–only (it has nothing to do with the Vue integration). Once it is set, the values are static. That's why the [`uploadUrl`](https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_adapters_simpleuploadadapter-SimpleUploadConfig.html#member-uploadUrl) cannot be changed during the runtime.

To make it dynamic, you're gonna need a [custom adapter implementation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) that, for instance, accepts a function as `uploadUrl` (so you can return your dynamic URL).

**Comment by NegativeDearc** [comment]
Thanks for your explaination. Will try by follow your instruction.

**Comment by rhysstubbs** [comment]
This is a shame, I totally get that CK is not just a vue library but something as common as this should be apart of the library. If anyone stumbles across this and is trying to workout whether a custom adapter is worth it, I would 100% recommend going down that route as you'll find an integration much easier.
